### PR TITLE
FEC: do not drop leading packets in reader

### PR DESCRIPTION
**Pull request by dshil**
Closes: #186

### CODE REVIEW

**Comment by gavv** [comment]
LGTM. How did you test this?

**Comment by dshil** [comment]
> LGTM. How did you test this?

I just run the tests but I did not test in the real scenario when ROC looses a lot of packets
and accidentally meets this case.

Probably I can put a hack in which I will drop each first packet in a block and listen how the ROC behaves.

**Comment by gavv** [comment]
I think you can just start the sender in the background and then restart the receiver frequently. This way receiver will be usually started in a middle of a block.

The first thing is just to check that it works.

The second thing is to do this on a bit noisy channel, where packets are lost regularly, and see whether this patch increases the probability of glitches on session start, or not.

**Comment by dshil** [comment]
Well, several checks was performed:

* As you mentioned before. I started sender in the background and randomly
  started the receiver. All worked as expected.

* Emulate the noisy channel:

```sh
# Setup 250ms latency + 15% of packet loss.
sudo tc qdisc add dev lo root handle 1:0 netem delay 250msec loss 15%

# Restore the initial behaviour.
sudo tc qdisc del dev lo root
```

I've tested the channel with parameters above and did not see any problems.

P.S. I would recommend you to try to increase the % of packet loss.
ROC recovers packets very well.

I think we can merge it.

**Comment by gavv** [comment]
Well, you tested it not hard enough.

I've patched the sender to drop every 7th packet to emulate frequent drops:

```
--- a/src/modules/roc_netio/target_uv/roc_netio/udp_sender.cpp
+++ b/src/modules/roc_netio/target_uv/roc_netio/udp_sender.cpp
@@ -127,6 +127,9 @@ void UDPSender::write(const packet::PacketPtr& pp) {
         roc_panic("udp sender: unexpected packet w/o data");
     }
 
+    static int C = 0;
+    if (C++ % 7 == 0) return;
+
     {
         core::Mutex::Lock lock(mutex_);
```

Then I started sender in one terminal:

```
roc-send -vv -s rtp+rs8m:127.0.0.1:10001 -r rs8m:127.0.0.1:10002 -i ~/stash/loituma.wav
```

And executed this script in another one:

```
for x in `seq 1 30`; do timeout 1 roc-recv -vv -s rtp+rs8m::10001 -r rs8m::10002 ; done |& grep --line-buffered 'of decoder: repaired' | stdbuf -oL cut -d' ' -f7- | grep --line-buffered X
```

This script restarts roc-recv 30 times every one second and greps for packets that were lost and were not recovered.

Normally this loss ration is okay and roc recovers all losses. On develop branch the output is empty.

However on you branch the output is the following:

```
XXXXXXXXXXXX.....X.. ....x....
XXXXXXXXXXXXXX...X.. ....x....
XXXXXXXXXXXXXXXX.X.. ....x....
XXXXXXX.X......X.... ..x.....
XXXXXXXXXX.....X.... ..x.....
XXXXXXXXXXXXX..X.... ..x.....
XXXXXXXXXXXXXX.X.... ..x.....
XXXXXXXXXXXXXXXXXX.. ..x.....
XXXXXXXXX....X...... x......x.
XXXXXXXXXXXX.X...... x......x.
XXXXXXXXXXXXXXXX.... x......x.
XXXXXXXXXXXXXXXXXXX. x......x.
XXXXXXXXX..X......X. .....x...
XXXXXXXXXX.X......X. .....x...
XXXXXXXXXXXXXX....X. .....x...
XXXXXXXXXXXXXXXXX.X. .....x...
XXXXXXXX.X......X... ...x.....
XXXXXXXXXXXX....X... ...x.....
XXXXXXXXXXXXXXX.X... ...x.....
```

19 runs from total 30 runs had unrecovered losses.

Let's look at this line closer:

```
XXXXXXXXXXXX.....X.. ....x....
```

The leading `XXXXXXXXXXXX` indicates that we've started in the middle of a block. This is okay, and these `X` corresponds to the silence preceding the first played packet.

However the second half of the source block (`.....X..`) indicates that we were not able to recover one lost packet, obviously because we had not enough  packets to feed the FEC decoder.

So, *there is* a degradation. It seems that we need some smarter approach.

**Comment by gavv** [comment]
BTW, when we fix this, I think we also need a pipeline-level unit test for this situation.

**Comment by gavv** [comment]
(Postponed)

**Pull request closed without merging**
